# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcproject.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpcproject.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2a\n\x0bGrpcProject\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12(\n\rFetchResponse\x12\x08.Request\x1a\t.Response\"\x00\x30\x01\x42\x0fZ\r./grpcprojectb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcproject_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\r./grpcproject'
  _HELLOREQUEST._serialized_start=21
  _HELLOREQUEST._serialized_end=49
  _HELLOREPLY._serialized_start=51
  _HELLOREPLY._serialized_end=80
  _REQUEST._serialized_start=82
  _REQUEST._serialized_end=103
  _RESPONSE._serialized_start=105
  _RESPONSE._serialized_end=131
  _GRPCPROJECT._serialized_start=133
  _GRPCPROJECT._serialized_end=230
# @@protoc_insertion_point(module_scope)
