run_server:
	docker compose up

run_zoo_1:
	docker exec -it lab07-zoo1-1 zkCli.sh -server zoo1:2181

run_zoo_2:
	docker exec -it lab07-zoo2-1 zkCli.sh -server zoo2:2181

run_zoo_3:
	docker exec -it lab07-zoo3-1 zkCli.sh -server zoo3:2181
