generate_java:
	slice2java --output-dir generated slice/zadi4.ice

generate_py:
	slice2py --output-dir client slice/zadi4.ice

run_py:
	echo "if you really want to run py I suggest to move to client directory. Good luck!"